name: Deploy to Firebase Hosting on merge

'on':
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
        
      # Create .env file with Firebase config
      - name: Create .env file
        run: |
          touch .env
          # Firebase configuration (non-sensitive public client-side values)
          echo "VITE_FIREBASE_AUTH_DOMAIN=jadeg-money.firebaseapp.com" >> .env
          echo "VITE_FIREBASE_DATABASE_URL=https://jadeg-money-default-rtdb.firebaseio.com" >> .env
          echo "VITE_FIREBASE_PROJECT_ID=jadeg-money" >> .env
          echo "VITE_FIREBASE_STORAGE_BUCKET=jadeg-money.firebasestorage.app" >> .env
          echo "VITE_FIREBASE_MESSAGING_SENDER_ID=851428868473" >> .env
          echo "VITE_FIREBASE_APP_ID=1:851428868473:web:cb6fb3fd76aae79eb1efa8" >> .env
          echo "VITE_FIREBASE_MEASUREMENT_ID=G-JVR230KBQV" >> .env
          echo "VITE_FIREBASE_API_KEY=AIzaSyA9DHumqRPnQn2dOv_ZERF2HvCATcYU0Bc" >> .env
          
          # Optional AI keys can be added manually if needed after deployment
          # These aren't needed for the core application functionality
      
      - name: Build project
        run: npm run build
      
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_JADEG_MONEY }}'
          channelId: live
          projectId: 'jadeg-money'
